### ISSUE TITLE
Casting Magic that is on items

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1225]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

I found that trying to cast spells from items such as the Imp Staff like (Priest's Curse / ID 2814)
that is built into the Staff crashes the server.

### The log given by the failure.

Appears in the ACE_Log.txt file

2019-01-03 15:02:56,898 [World Manager] DEBUG (ACE.DatLoader.DatDatabase) Unable to find object_id AAB2FFFE in Cell

**Comment by gmriggs** [comment]
Started to address this issue in https://github.com/ACEmulator/ACE/pull/1230

This is not a full solution, but it does fix the crashing, and gets the spell to cast

Open questions:

- Should there be a windup animation when casting spells built into the wand?
- Should those spells use the 'Spellcraft' from the wand for the attack skill level, instead of the player's magic skill?
- Should those spells use mana from the wand, instead of from the player's mana?

Any other details / videos of spells being cast from wands would also be helpful!

Thanks for the bug report :)

**Comment by gmriggs** [comment]
Ok, I think a lot of these points should be accounted for now:

The casting implements with built-in spells did indeed have custom casting animations. These were found in PropertyDID.UseUserAnimation.

The War Magic: 270 activation requirement was not showing up in the appraisal window. This is another field that required munging in AppraiseInfo, where PropertyDID.ItemSkillLimit is converted into PropertyInt.AppraisalItemSkill for the client display

The activation checks were added to augment the wield checks. If the player doesn't meet the activation requirements (Arcane Lore 50, War Magic 270) for the Imp Staff, they can still wield it, but they now get the appropriate error when trying to cast Priest's Curse

The amount of mana consumed from casting Priest's Curse now comes from the ItemManaCost field. As per the staff description, this is reduced with Mana Conversion

Casting Priest's Curse now uses the Item Spellcraft as the attack skill level

Open questions:

Did casting Priest's Curse have any chance of fizzle?

**Comment by gmriggs** [comment]
All of these issues should be resolved now in https://github.com/ACEmulator/ACE/pull/1230
