### ISSUE TITLE
Patron-Vassal XP Passup Bugs

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1269]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

When a Vassal passes XP up to a Patron, it is at first only represented in game messages and within Total XP bar. Only raising a skill will commit the experience into Unassigned Experience. 
Further, the Total XP that was passed up will transform the Total XP of the Patron to a negative mirrored value of itself after XP is gained from any other methods

### Mention any other details that might be useful.

Screenshot in Discord

**Comment by gmriggs** [comment]
Having some difficulty reproing this bug... can you provide the exact repro steps, possibly a video of the exact steps?

Trying all of the scenarios I can think of, it seems to be handling everything for all of the cases I've tried so far..

**Comment by gmriggs** [comment]
Not sure if this fixes anything (I have still been unable to repro this bug once so far) but I cleaned up a bunch of this code in https://github.com/ACEmulator/ACE/pull/1291, and also added the 'allegiance xp received' per-vassal field

**Comment by gmriggs** [comment]
After talking about this more with @someeodtech , we have both been unable to repro this bug again. It seems to be some very odd exception, and is possibly already fixed in https://github.com/ACEmulator/ACE/pull/1291

If anyone can get this bug to happen again, please provide as much info as possible, any any possible repro steps. If this bug does happen, it is most likely just a display bug in the client... the player does not receive the 'level up' packet for some reason, and 'XP until next level' appears negative. If you relog, and XP should display as normal.
