### ISSUE TITLE
Sentry NPC runs in quick circles

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1455]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Sentry NPC run's in quick circles, abnormal behavior

https://megaupload.nz/AdG495u4bc/Asheron_s_Call_2019-02-20_19-51-16_mp4

Your location is: 0xAAB30004 [4.926544 83.786240 116.005005] 0.756161 0.000000 0.000000 -0.654385

**Comment by cyberkiller6** [comment]
Tested on commit #1454 and ACE World Database v0.9.18

**Comment by gmriggs** [comment]
After looking into this some more, and setting the Move* emotes to walk instead of run, I found that the Holtburg sentries would still run in circles. I believe this to be a data bug - the positions for the 'MoveToPos' emotes for the Holtburg sentries contain positions that are not on the ground (either above the ground, or below the ground) so the sentry keeps running around the target position, because it can never reach it.
