### ISSUE TITLE
Player Death drops half of each stack of pyreals, pyreals dropped not on corpse

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1535]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Create a character
Create three stacks of 100k pyreals
Die.

Instead of dropping 150k pyreals, you will drop 50k pyreals, 50k pyreals and 50k pyreals. Also the pyreals will vanish instead of being on your player's corpse.

### Desired functionality.
You should drop one stack of 150k pyreals and they should be located on the player's corpse

**Comment by cyberkiller6** [comment]
So apparently I am wrong and the pyreals did vanish at end of retail. However, the death message should only list the pyreals once. Should display half the number of total pyreals, not half of each stack.

**Comment by gmriggs** [comment]
Some notes:

- The max size for a pyreal stack is 25k, so tested with 3x stacks of 10k pyreals each, instead of the 100k pyreal stacks in the original issue

- The exact message printed by this scenario was: You've lost 10,000 Pyreals, 5,000 Pyreals, your Leather Boots, your Pants, and your Jerkin!

So not exactly splitting each of the 3x 10k stacks in half, but this is the way the SpendCurrency() function works... it sorts all of the Pyreal stacks in order from smallest to largest, and then starts consuming the amount of coins

The death message has been consolidated, so the total amount of pyreals dropped is listed, instead of each of the individual stacks that were consumed from.

After much discussion about whether or not pyreals were destroyed on death, or dropped on the corpse (with people certain it seemed to work both ways), it was learned that pyreals originally dropped on death, but at some point during retail, this was changed to destroyed.

The server defaults to end of retail settings (destroyed on death), but a new config option has been added, if the server admin wishes to run with coins dropped on player corpses, similar to the earlier days

To enable this setting: /modifybool corpse_destroy_pyreals false
