### ISSUE TITLE
Logs should go to separate window, and filesystem

### ISSUE THREAD

**Issue by zbuc** [ACEmulator/ACE#31]
Logs should go in a separate window from the main `ACE >>` command prompt so admins aren't frustrated with information stomping commands as they're being typed.

Might as well add a `Config.json` option to log them to the filesystem and set verbosity at the same time.

**Comment by zbuc** [comment]
I think this would involve:

1) Add the log path and verbosity flags to the `Config.json`
2) Create a new persistent logging thread that can operate off a queue of log message tasks, sending them to the filesystem
3) Create a new window to display log messages, streamed from the filesystem
4) Replace `Console.WriteLine` messages used for logging with calls to queue log message tasks on the logging thread

I'm not a .NET developer, but it looks like these classes might be useful: https://msdn.microsoft.com/en-us/library/microsoft.visualbasic.logging.filelogtracelistener.aspx

**Comment by Mogwai-AC** [comment]
.Net guy recommendation: use NLog or Log4Net.  both are well known, reliable frameworks for logging.

**Comment by Zegeger** [comment]
I think ideally it should be written such that different logging listeners could be swapped in allowing a logger of ones choice.
My recommendation would be to do ETW logging.  Its more cumbersome to handle the resulting logs, but there is a very low perf overhead, allowing you to hit 10k+ entries per second without stealing perf.  This is what things like Exchange/Skype for Business servers use.
I could work on something like this.

**Comment by fantoms** [comment]
log4net seems to be working very well now:

- Instance the ILog interface within an object, to gain Logging capabilities, within a scope:
`private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);`
- The log file path can be set in the `log4net.config` file:
`<file value="C:\ACE\logs\ACE_Log.txt" />`
- Currently, all logging levels are saved to disk in the `ACE_Log.txt` file. The log files are getting quite large, mainly due to the packet debug info.:
`<threshold value="ALL" />`
- Utilizing the Log.info() will currently send the log message to the console, as well.
