### ISSUE TITLE
Recipes with TinkeringMaterial items that are not traditional salvage do not function properly

### ISSUE THREAD

**Issue by OptimShi** [ACEmulator/ACE#3592]
- [ X] bug report -> please search issues before submitting

### Repro steps.

Attempting to re-create the Mucor Enhanced Weapons, the Mucor-Altered Granite/Mahagony/Opal are of a ITEM_TYPE_INT "TinkeringMaterial". These items will currently automatically go through the Tinkering/Salvaging pipeline because of that and attempt to apply them as a salvage, using a salvage application skill check.

### Desired functionality.

Should work as expected, doing a standard skill check and following the recipe using proper difficulty, and other standard recipe steps.

### Mention any other details that might be useful.

Current work-around is to change the Mucor-Altered <Material> item from TinkeringMaterial to a different ItemType.

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/3593

ItemType can now be set to the retail values, and ItemType now makes no determination in whether or not the tinkering code is used

Note that the only "tinkering code" in the system now are the tinkering difficulty formulas. This was solely determined by the salvage_Type field. salvage_Type 0 is for normal recipes that use the normal built-in difficulties in the recipe.difficulty field. salvage_Type 1 is for tinkering (tinkering difficulty calculation, difficulty on the recipe is unused here) and salvage_Type 2 is for imbues, which is similar to tinkering, except with the / 3 and imbue aug addons.

salvage_Type could be better thought of as a difficulty_Type. ie., just because something is a bag of salvage, doesn't mean it gets salvage_Type set. See leather, sandstone, and ivory salvage -- leather especially, since it was in py16. All of these are bags of salvage, yet they have salvage_Type 0, so they can use the regular recipe difficulty formula.

So for the Mucor-Altered "salvages", salvage_Type should be set to 0 for those.
