### ISSUE TITLE
Tattercoat spell from composite bow does not change damage dealt from bow

### ISSUE THREAD

**Issue by bc4253** [ACEmulator/ACE#3928]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Using Compound Bow with Fine Handle on a MOB with lots of hp, fire arrows until the bow casts Tattercoat on the MOB, then fire more arrows.  notice that the arrow damage is the same before and after the Tattercoat spell is applied to the MOB.

**Comment by gmriggs** [comment]
Which mob are you procing Tattercoat on, specifically? Is the mob actually wearing pieces of armor?

**Comment by bc4253** [comment]
ah, good point.  the Dire champions I have been testing it out on I don't think have armor.

**Comment by gmriggs** [comment]
Investigated this some more. Despite the description for Tattercoat saying it affects armor and shields, when the Composite Bow procced this spell on a creature in retail, it could only affect their shield, and not their armor. So my initial guess about the creature not wearing any armor wasn't exactly correctly either.

The bug you reported was indeed a bug in ACE for mobs wielding a shield, and that has been fixed in https://github.com/ACEmulator/ACE/pull/3929. Aside from that, this spell didn't have any effect on mobs not wielding a shield, and no message was displayed to the user / the proc didn't happen in this case (same as current ACE behavior)

**Comment by bc4253** [comment]
So that makes sense.  I have to find a creature with a lot of hits that doesnt quickly kill me that wears armor to try this out on.  I do see the message that Tattercoat procs against MOBs with no armor, such as Virindi Custodian.

**Comment by gmriggs** [comment]
In current ACE, it's no effective against any mobs, regardless if they are wearing armor pieces, or have a shield. The message that it's proccing on the actual mob is just a placebo currently -- it currently has no effect.

In the updated version linked above, armorless and armored mobs effectively remain the same, and the spell is ineffective against them. No message is displayed in the updated version in this scenario.

Also in the updated version, if a mob is wielding a shield, the spell successfully procs, and shows the message 'You cast Tattercoat on <shield name>', instead of the name of the mob. This was confirmed with retail pcaps, and this behavior is exactly the same as if you were to target the mob directly, and cast Tattercoat on them,

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/3929
